/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.btbuoi9;

import javax.swing.JFrame;

/**
 *
 * @author datcy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setSize(800, 800);
        addControl();
        notLoginYet();
    }

    public void addControl() {
        System.out.println("addControl Main");

        mnDangXuat.addActionListener((e) -> {
            logoutAction();
        });
        mnDangNhap.addActionListener((e) -> {
            System.out.println("click DN");
            frmDangNhap frmDN = new frmDangNhap(this, true);
            frmDN.setVisible(true);
            if (frmDN.isbKQDN()) {
                this.mnHoaDon.setEnabled(true);
                this.mnLoaiSach.setEnabled(true);
                this.mnPhieuNhap.setEnabled(true);
                this.mnLoaiSach.setEnabled(true);
                this.mnDangXuat.setEnabled(true);
                this.mnDangNhap.setEnabled(false);
            }
        });
        mnLoaiSach.addActionListener((e) -> {
            frmLoaiSach frm = new frmLoaiSach();
            frm.setVisible(true);
            frm.pack();
            this.dskPane.add(frm);
        });
    }

    public void notLoginYet() {
        this.mnHoaDon.setEnabled(false);
        this.mnLoaiSach.setEnabled(false);
        this.mnPhieuNhap.setEnabled(false);
        this.mnLoaiSach.setEnabled(false);
        this.mnDangXuat.setEnabled(false);
    }

    public void logoutAction() {
        this.mnHoaDon.setEnabled(false);
        this.mnLoaiSach.setEnabled(false);
        this.mnPhieuNhap.setEnabled(false);
        this.mnLoaiSach.setEnabled(false);
        this.mnDangXuat.setEnabled(false);
        this.mnDangNhap.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnHT = new javax.swing.JMenu();
        mnDangNhap = new javax.swing.JMenuItem();
        mnDangXuat = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenuItem();
        mnQL = new javax.swing.JMenu();
        mnLoaiSach = new javax.swing.JMenuItem();
        mnSach = new javax.swing.JMenuItem();
        mnHoaDon = new javax.swing.JMenuItem();
        mnPhieuNhap = new javax.swing.JMenuItem();
        mnHuongDan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPaneLayout = new javax.swing.GroupLayout(dskPane);
        dskPane.setLayout(dskPaneLayout);
        dskPaneLayout.setHorizontalGroup(
            dskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        dskPaneLayout.setVerticalGroup(
            dskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        mnHT.setText("Hệ thống");

        mnDangNhap.setText("Đăng nhập");
        mnHT.add(mnDangNhap);

        mnDangXuat.setText("Đăng xuất");
        mnDangXuat.setToolTipText("");
        mnHT.add(mnDangXuat);

        mnThoat.setText("Thoát");
        mnHT.add(mnThoat);

        jMenuBar1.add(mnHT);

        mnQL.setText("Quản lý");

        mnLoaiSach.setText("Loại sách");
        mnQL.add(mnLoaiSach);

        mnSach.setText("Sách");
        mnQL.add(mnSach);

        mnHoaDon.setText("Hóa đơn");
        mnQL.add(mnHoaDon);

        mnPhieuNhap.setText("Phiếu nhập sách");
        mnQL.add(mnPhieuNhap);

        jMenuBar1.add(mnQL);

        mnHuongDan.setText("Hướng dẫn");
        jMenuBar1.add(mnHuongDan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnDangNhap;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenu mnHT;
    private javax.swing.JMenuItem mnHoaDon;
    private javax.swing.JMenu mnHuongDan;
    private javax.swing.JMenuItem mnLoaiSach;
    private javax.swing.JMenuItem mnPhieuNhap;
    private javax.swing.JMenu mnQL;
    private javax.swing.JMenuItem mnSach;
    private javax.swing.JMenuItem mnThoat;
    // End of variables declaration//GEN-END:variables
}
